---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure tzdata package is installed (Linux).
  package:
    name: tzdata
    state: present
  when: ansible_system == "Linux"

- name: Set timezone
  timezone:
    name: "{{ ntp_timezone }}"

- name: Installation des paquets ntp et ntpdate
  package: name={{ item }} state=latest
  with_items:
      - ntp
      - ntpdate
  notify: run ntpdate
  tags: install_package

- name: Stop service ntp if running
  service:
    name: "{{ ntpd_service_name }}"
    state: stopped

- name: run ntpdate on hosts
  command: "echo 1 >/dev/null"
  notify: run ntpdate 

- name: Importation du fichier de configuration du serveur de temps (NTP)
  template: src=ntp.conf.j2 dest=/etc/ntp.conf backup=yes
  notify:
     - enable ntpd
     - restart ntpd
