---
- name: run ntpdate
  command: "{{ binary_ntpdate_location }} {{ ntpservers[0] }}"

- name: enable ntpd
  service:  name={{ ntpd_service_name }} enabled=yes

- name: restart ntpd
  service:  name={{ ntpd_service_name }} state=restarted

